spring.datasource.url=jdbc:mysql://br1.mmddkk.dev.br:3306/loxecutivo?useTimezone=true&serverTimezone=UTC
spring.datasource.username=aula
spring.datasource.password=aula123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.main.banner-mode=console
spring.application.name=loxecutivo